org: upstandfm
app: api
service: files-api

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.upstand.fm
    basePath: files
    stage: ${opt:stage, 'prod'}
    createRoute53Record: false
  cors:
    origin: '*'
  authorizer:
    arn: ${secrets:AUTH0_AUTHORIZER_ARN}
    resultTtlInSeconds: 60
    identitySource: method.request.header.Authorization
    # Note that Bearer must be capitalized
    identityValidationExpression: '^Bearer [-0-9a-zA-z\.]*$'
    type: token

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'eu-central-1'}
  cfnRole: ${secrets:CFN_ROLE_ARN}
  memorySize: 128
  timeout: 3
  deploymentBucket:
    name: upstandfm-deployments
    serverSideEncryption: AES256 # when using server-side encryption
  environment:
    # Reuse TCP connection to reduce request latency
    # For more info see:
    # https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#24630
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    CORS_ALLOW_ORIGIN: ${self:custom.cors.origin}
    UPLOAD_FILE_SCOPE: 'upload:file'
    DOWNLOAD_FILE_SCOPE: 'download:file'
    # The ARN has the format "arn:aws:s3:::bucketName"
    # Splitting on ":::" gives us the name
    S3_RECORDINGS_BUCKET_NAME:
      'Fn::Select':
        ['1', { 'Fn::Split': [':::', '${state:infra.recordingsBucketArn}'] }]
    S3_TRANSCODED_RECORDINGS_BUCKET_NAME:
      'Fn::Select':
        [
          '1',
          {
            'Fn::Split':
              [':::', '${state:infra.transcodedRecordingsBucketArn}'],
          },
        ]
    # The ARN has the format "arn:aws:dynamodb:::table/tableName"
    # Splitting on "/" gives us the name
    DYNAMODB_STANDUPS_TABLE_NAME:
      'Fn::Select':
        ['1', { 'Fn::Split': ['/', '${state:infra.standupsTableArn}'] }]
  # See: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_actions-resources-contextkeys.html
  iamRoleStatements:
    # Custom: Allows interacting with media objects in the bucket (indirectly)
    - Effect: Allow
      Action:
        - s3:PutObject
      # MUST contain "/*" because resource type is "object"
      Resource:
        'Fn::Join': ['/', ['${state:infra.recordingsBucketArn}', '*']]
    - Effect: Allow
      Action:
        - s3:GetObject
      # MUST contain "/*" because resource type is "object"
      Resource:
        'Fn::Join': ['/', ['${state:infra.transcodedRecordingsBucketArn}', '*']]
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource: ${state:infra.standupsTableArn}

package:
  exclude:
    - ./*
    - ./**/*.test.js
  include:
    - node_modules
    - src

functions:
  createStandupUpdateUploadUrl:
    handler: src/handler.createStandupUpdateUploadUrl
    description: Creates a signed URL to upload a standup update
    events:
      - http:
          method: post
          path: /standup-update/upload
          cors: ${self:custom.cors}
          authorizer: ${self:custom.authorizer}
  createStandupUpdateDownloadUrl:
    handler: src/handler.createStandupUpdateDownloadUrl
    description: Creates a signed URL to download a standup update
    events:
      - http:
          method: post
          path: /standup-update/download
          cors: ${self:custom.cors}
          authorizer: ${self:custom.authorizer}

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    GatewayResponseDefault5XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
